import type { FilteredResult } from '@/types/custom'
import type { Order } from './types'
import dayjs from 'dayjs'

export const ordersList: Order[] = [
  {
    orderId: '#002162580',
    trackId: 'Mo-67710768',
    canceledOrder: 0,
    paymentMethod: 'Fatora',
    totalAmount: '150.000',
    deliveryTime: '2025-07-05T08:00:00Z',
    estTime: '60',
    dispatch: true,
    tags: ['VIP'],
    deliveryTimer: '00:05:00',
    status: 'Pending',
    translations: {
      customerName: { en: 'Alice Smith', ar: 'أليس سميث' },
      restaurant: { en: 'Sunrise Cafe', ar: 'كافيه الشروق' },
      area: { en: 'Downtown', ar: 'وسط المدينة' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Pending', ar: 'قيد الانتظار' },
    },
  },
  {
    orderId: '#002162581',
    trackId: 'Mo-67710769',
    canceledOrder: 1,
    paymentMethod: 'Cash',
    totalAmount: '300.500',
    deliveryTime: '2025-07-05T08:30:00Z',
    estTime: '45',
    dispatch: false,
    tags: ['FirstOrder'],
    deliveryTimer: '00:10:00',
    status: 'Accepted',
    translations: {
      customerName: { en: 'Bob Johnson', ar: 'بوب جونسون' },
      restaurant: { en: 'Green Garden', ar: 'الحديقة الخضراء' },
      area: { en: 'Al Mozeh', ar: 'المزة' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Accepted', ar: 'مقبول' },
    },
  },
  {
    orderId: '#002162582',
    trackId: 'Mo-67710770',
    canceledOrder: 0,
    paymentMethod: 'eCash',
    totalAmount: '120.000',
    deliveryTime: '2025-07-05T09:00:00Z',
    estTime: '30',
    dispatch: true,
    tags: ['MovoPlus'],
    deliveryTimer: '00:15:00',
    status: 'Preparing',
    translations: {
      customerName: { en: 'Charlie Davis', ar: 'تشارلي ديفيس' },
      restaurant: { en: 'Ocean Breeze', ar: 'نسيم البحر' },
      area: { en: 'Al Rashid', ar: 'الرشيد' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Preparing', ar: 'يتم التحضير' },
    },
  },
  {
    orderId: '#002162583',
    trackId: 'Mo-67710771',
    canceledOrder: 2,
    paymentMethod: 'Fatora',
    totalAmount: '500.000',
    deliveryTime: '2025-07-05T09:30:00Z',
    estTime: '40',
    dispatch: true,
    tags: [],
    deliveryTimer: '00:20:00',
    status: 'Collecting',
    translations: {
      customerName: { en: 'Diana Evans', ar: 'ديانا إيفانز' },
      restaurant: { en: 'Mountain View', ar: 'منظر الجبل' },
      area: { en: 'Al Mohafaza', ar: 'المحافظة' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Collecting', ar: 'جارٍ الجمع' },
    },
  },
  {
    orderId: '#002162584',
    trackId: 'Mo-67710772',
    canceledOrder: 1,
    paymentMethod: 'Cash',
    totalAmount: '75.250',
    deliveryTime: '2025-07-05T10:00:00Z',
    estTime: '50',
    dispatch: false,
    tags: ['VIP', 'MovoPlus'],
    deliveryTimer: '00:25:00',
    status: 'OutForDelivery',
    translations: {
      customerName: { en: 'Ethan Ford', ar: 'إيثان فورد' },
      restaurant: { en: 'City Lights', ar: 'أضواء المدينة' },
      area: { en: 'Al Baraka', ar: 'البركة' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'OutForDelivery', ar: 'خارج للتوصيل' },
    },
  },
  {
    orderId: '#002162585',
    trackId: 'Mo-67710773',
    canceledOrder: 0,
    paymentMethod: 'eCash',
    totalAmount: '220.000',
    deliveryTime: '2025-07-05T10:30:00Z',
    estTime: '35',
    dispatch: true,
    tags: ['FirstOrder'],
    deliveryTimer: '00:30:00',
    status: 'Delivered',
    translations: {
      customerName: { en: 'Fiona Green', ar: 'فيونا غرين' },
      restaurant: { en: 'Sunset Grill', ar: 'شواية الغروب' },
      area: { en: 'Al Safa', ar: 'الصفا' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Delivered', ar: 'تم التوصيل' },
    },
  },
  {
    orderId: '#002162586',
    trackId: 'Mo-67710774',
    canceledOrder: 3,
    paymentMethod: 'Cash',
    totalAmount: '350.500',
    deliveryTime: '2025-07-05T11:00:00Z',
    estTime: '45',
    dispatch: false,
    tags: ['VIP'],
    deliveryTimer: '00:35:00',
    status: 'Hold',
    translations: {
      customerName: { en: 'George Harris', ar: 'جورج هاريس' },
      restaurant: { en: 'Palm Tree', ar: 'نخلة' },
      area: { en: 'Al Jazeera', ar: 'الجزيرة' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Hold', ar: 'معلق' },
    },
  },
  {
    orderId: '#002162587',
    trackId: 'Mo-67710775',
    canceledOrder: 2,
    paymentMethod: 'Fatora',
    totalAmount: '180.750',
    deliveryTime: '2025-07-05T11:30:00Z',
    estTime: '40',
    dispatch: true,
    tags: ['MovoPlus'],
    deliveryTimer: '00:40:00',
    status: 'Refund',
    translations: {
      customerName: { en: 'Hannah Ivory', ar: 'هانا إيفوري' },
      restaurant: { en: 'Blue Lagoon', ar: 'البحيرة الزرقاء' },
      area: { en: 'Al Andalus', ar: 'الأندلس' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Refund', ar: 'تم الاسترداد' },
    },
  },
  {
    orderId: '#002162588',
    trackId: 'Mo-67710776',
    canceledOrder: 0,
    paymentMethod: 'Cash',
    totalAmount: '400.000',
    deliveryTime: '2025-07-05T12:00:00Z',
    estTime: '55',
    dispatch: true,
    tags: ['VIP', 'FirstOrder'],
    deliveryTimer: '00:45:00',
    status: 'Arrived',
    translations: {
      customerName: { en: 'Ian Jones', ar: 'إيان جونز' },
      restaurant: { en: 'Red Rock', ar: 'الصخرة الحمراء' },
      area: { en: 'Al Wadi', ar: 'الوادي' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Arrived', ar: 'وصل' },
    },
  },
  {
    orderId: '#002162589',
    trackId: 'Mo-67710777',
    canceledOrder: 1,
    paymentMethod: 'Fatora',
    totalAmount: '130.000',
    deliveryTime: '2025-07-05T12:30:00Z',
    estTime: '30',
    dispatch: true,
    tags: ['FirstOrder'],
    deliveryTimer: '00:50:00',
    status: 'Pending',
    translations: {
      customerName: { en: 'Jack King', ar: 'جاك كينغ' },
      restaurant: { en: 'Lakeside', ar: 'جانب البحيرة' },
      area: { en: 'Al Quds', ar: 'القدس' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Pending', ar: 'قيد الانتظار' },
    },
  },
  {
    orderId: '#002162590',
    trackId: 'Mo-67710778',
    canceledOrder: 0,
    paymentMethod: 'Cash',
    totalAmount: '280.250',
    deliveryTime: '2025-07-05T13:00:00Z',
    estTime: '40',
    dispatch: false,
    tags: ['MovoPlus'],
    deliveryTimer: '00:55:00',
    status: 'OutForDelivery',
    translations: {
      customerName: { en: 'Karen Lee', ar: 'كارين لي' },
      restaurant: { en: 'Golden Spoon', ar: 'الملعقة الذهبية' },
      area: { en: 'Al Basra', ar: 'البصرة' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'OutForDelivery', ar: 'خارج للتوصيل' },
    },
  },
  {
    orderId: '#002162591',
    trackId: 'Mo-67710779',
    canceledOrder: 0,
    paymentMethod: 'eCash',
    totalAmount: '330.000',
    deliveryTime: '2025-07-05T13:30:00Z',
    estTime: '30',
    dispatch: true,
    tags: ['VIP'],
    deliveryTimer: '01:00:00',
    status: 'Accepted',
    translations: {
      customerName: { en: 'Liam Moore', ar: 'ليام مور' },
      restaurant: { en: 'The Great Table', ar: 'الطاولة الكبرى' },
      area: { en: 'Al Noor', ar: 'النور' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Scheduled', ar: 'مجدول' },
    },
  },
  {
    orderId: '#002162592',
    trackId: 'Mo-67710780',
    canceledOrder: 0,
    paymentMethod: 'Fatora',
    totalAmount: '210.000',
    deliveryTime: '2025-07-05T14:00:00Z',
    estTime: '45',
    dispatch: false,
    tags: ['MovoPlus'],
    deliveryTimer: '01:05:00',
    status: 'Preparing',
    translations: {
      customerName: { en: 'Mia Nelson', ar: 'ميا نلسون' },
      restaurant: { en: 'Spice Route', ar: 'طريق التوابل' },
      area: { en: 'Al Jameela', ar: 'الجميلة' },
      transType: { en: 'Movo', ar: 'موفو' },
      status: { en: 'Scheduled', ar: 'مجدول' },
    },
  },
].map((order, index) => {
  const deliveryTime = dayjs(order.deliveryTime)
  const timePassedMs = dayjs().diff(deliveryTime)
  return {
    ...order,
    id: index + 1,
    timePassed: timePassedMs.toString(),
    total: 180000,
  }
})

export function fetchLocalizedOrders(): FilteredResult<Order> {
  return {
    items: ordersList,
    totalCount: ordersList.length,
  }
}
